
# Handling Reading
safe: false
encoding: UTF-8
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown:     kramdown
highlighter:  pygments
lsi:          false

#Server
baseurl: http://agileframework.org

# Outputting
permalink:     /kb/:categories/:title
paginate_path: /page:num
timezone:      null

redcarpet:
    extensions: [ "fenced_code_blocks", "hard_wrap","autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify","no_intra_emphasis"]
    
kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart
  use_coderay: true
  syntax_highlighter: rouge
  coderay:
    coderay_line_numbers:  nil
    
#Dependencies
#markdown: redcarpet
#highlighter: pygments
#permalink: /kb/:categories/:title
#permalink: /:categories/:title.html
#permalink: pretty
