#Dependencies
markdown: redcarpet
highlighter: pygments
permalink: /kb/:categories/:title
#permalink: /:categories/:title.html
#permalink: pretty
redcarpet:
extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]
#Server
baseurl: http://agileframework.org
encoding: UTF-8
