#Dependencies
markdown: redcarpet
highlighter: pygments
permalink: /kb/:categories/:title
#permalink: /:categories/:title.html
#permalink: pretty
safe: false
#Server
baseurl: http://agileframework.org
encoding: UTF-8
