#Dependencies
#markdown: kramdown
#highlighter: rouge
#markdown: redcarpet
#permalink: /:categories/:title.html
permalink: /:title.html
pygments: true

pygments: true

#Server
baseurl: /
encoding: UTF-8
