# Handling Reading
safe: false
encoding: UTF-8
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown:     kramdown
highlighter:  pygments
lsi:          false

#Server
baseurl: http://agileframework.org

# Outputting
permalink:     /kb/:categories/:title
#paginate_path: /page:num
#timezone:      null


# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1
  
#redcarpet:
    #extensions: ["no_intra_emphasis","fenced_code_blocks","autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify"]    
    
    
    #extensions: [ "fenced_code_blocks", "hard_wrap","autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify","no_intra_emphasis"]
#Dependencies
#markdown: redcarpet
#highlighter: pygments
#permalink: /kb/:categories/:title
#permalink: /:categories/:title.html
#permalink: pretty
