#Dependencies
#markdown: kramdown
#highlighter: rouge
markdown: redcarpet
#permalink: /:categories/:title.html
permalink: /:title.html
url: 
lsi: false
pygments: true
safe: true
auto: false

pygments: true

#Server
baseurl: /
encoding: UTF-8
