#Dependencies
markdown: kramdown
highlighter: pygments
permalink: /kb/:categories/:title
#permalink: /:categories/:title.html
#permalink: pretty

#Server
baseurl: http://agileframework.org
encoding: UTF-8
